package shared;

public enum MessageType {
    LOGIN, REGISTER, LOGIN_SUCCESS, LOGIN_FAILURE, REGISTER_SUCCESS, REGISTER_FAILURE,
    LOGOUT, LOGOUT_SUCCESS, LOGOUT_FAILURE,
    CHAT,
    SEARCH_USER, USER_FOUND, USER_NOT_FOUND,
    SEND_FRIEND_REQUEST, FRIEND_REQUEST_SENT, FRIEND_REQUEST_FAILED,
    VIEW_PENDING_REQUESTS, PENDING_REQUESTS_LIST,
    ACCEPT_FRIEND_REQUEST, FRIEND_ADDED, FRIEND_ADD_FAILED,
    REJECT_FRIEND_REQUEST, FRIEND_REQUEST_REJECTED, FRIEND_REQUEST_REJECT_FAILED,
    REMOVE_FRIEND, FRIEND_REMOVED, FRIEND_REMOVE_FAILED,
    LIST_FRIENDS, FRIENDS_LIST,
    CHANGE_PASSWORD, CHANGE_PASSWORD_SUCCESS, CHANGE_PASSWORD_FAILURE,
    UPDATE_PUBLIC_KEY, REQUEST_PUBLIC_KEY, PUBLIC_KEY_RESPONSE,
    HISTORY_REQUEST, HISTORY_RESPONSE,
    CHAT_MESSAGE, CHAT_STATE_UPDATE;
}